### ISSUE TITLE
Hope to add support for Simplified Chinese language.

### ISSUE THREAD

**Issue by Kauo7420** [Niestrat99/AT-Rewritten#130]
I spent a considerable amount of time translating the `custom-messages.yml` file of this plugin into Simplified Chinese. I hope that it will be accepted and utilized by more servers!

The following content is what I have translated:

```yaml

# 此消息文件使用了MiniMessage格式，这是MC新版本中的一种新的消息格式化形式。
# 关于这种格式化的更多信息可以在以下链接找到：https://docs.advntr.dev/minimessage/format.html#
# 如果您更倾向于使用旧版代码格式（例如 &a, &b 等），您仍然可以使用那种格式。
#
# 需要注意的是，尽管目前还没有确定，但这种格式在未来版本的AT中可能会被移除。
Common:
  # 消息的前缀，这个列表的第一个元素将作为<prefix>使用，
  # 列表中的每个后续元素可以用作<prefix:index>，其中index是列表中元素的索引。
  prefixes:
  - <aqua>↑</aqua> <dark_gray>»</dark_gray>
Teleport:
  # 这是在插件中用于标题和子标题的示例用法。
  # 此功能仅在1.8.8或更新版本中支持。
  eventBeforeTP_title:
    length: 80
    fade-in: 0
    fade-out: 10
    '0': <gray><b>传送中...
    '20': <aqua>></aqua> <gray><b>传送中...</b></gray> <aqua><
    '40': <aqua>>></aqua> <gray><b>传送中...</b></gray> <aqua><<
    '60': <aqua>>>> <b><yellow>已传送！</yellow></b> <aqua><<<
  eventBeforeTP_subtitle:
    '0': <aqua>请不要移动！
    '60': ''
  eventMovement_title:
    length: 60
    fade-in: 0
    fade-out: 10
    '0': <yellow><b>! <red>已取消</red>！
  eventBeforeTP: <prefix> <gray>传送将在<aqua><countdown>秒</aqua>后开始，请不要移动！
  eventBeforeTPMovementAllowed: <prefix> <gray>传送将在<aqua><countdown></aqua>秒后开始！
  eventTeleport: <prefix> <gray>正在传送...
  eventMovement: <prefix> <gray>由于移动，传送已被取消。
  teleportingToSpawn: <prefix> <gray>正在将您传送到出生点！
  teleporting: <prefix> <gray>正在传送到<aqua><player></aqua>！
  teleportingToHome: <prefix> <gray>正在传送到<aqua><home></aqua>！
  teleportingToHomeOther: <prefix> <gray>正在传送到<aqua><player></aqua>的家，<aqua><home></aqua>！
  teleportingToWarp: <prefix> <gray>正在将您传送到<aqua><warp></aqua>！
  teleportingPlayerToSelf: <prefix> <gray>正在将<aqua><player></aqua>传送到您这里！
  teleportingSelfToPlayer: <prefix> <gray>正在将您传送到<aqua><player></aqua>！
  teleportingToRandomPlace: <prefix> <gray>正在将您传送到一个随机位置！
  teleportingToLastLoc: <prefix> <gray>正在将您传送到您的最后位置！
  teleportedToOfflinePlayer: <prefix> <gray>已传送到离线玩家<aqua><player></aqua>！
  teleportedOfflinePlayerHere: <prefix> <gray>已将离线玩家<aqua><player></aqua>传送到您的位置！
Error:
  noPermission: <prefix> <gray>您没有使用此命令的权限！
  noPermissionSign: <prefix> <gray>您没有制作这个牌子的权限！
  featureDisabled: <prefix> <gray>此功能已被禁用！
  noRequests: <prefix> <gray>您没有任何待处理的请求！
  tpOff: <prefix> <aqua><player> <gray>已禁用他们的传送功能！
  tpBlock: <prefix> <aqua><player> <gray>已阻止您向他们发送请求！
  alreadyOn: <prefix> <gray>您的传送请求已经启用！
  alreadyOff: <prefix> <gray>您的传送请求已经禁用！
  alreadyBlocked: <prefix> <gray>此玩家已被阻止！
  neverBlocked: <prefix> <gray>此玩家从未被阻止！
  onCooldown: <prefix> <gray>请再等待<aqua><time></aqua>秒后使用此命令！
  requestSentToSelf: <prefix> <gray>您不能向自己发送请求！
  noSuchPlayer: <prefix> <gray>玩家目前不在线或不存在！
  alreadySentRequest: <prefix> <gray>您已经向<aqua><player></aqua>发送了请求！
  notEnoughGeneral: |2
        <prefix> <gray>您无法负担传送到那里的费用！
        <prefix> <gray>您需要<aqua><cost></aqua>！
  notEnoughEXP: |-
    <prefix> <gray>您的经验等级不足以传送到那里！
        <prefix> <gray>您至少需要<aqua><levels></aqua>经验等级！
  notEnoughEXPPoints: |-
    <prefix> <gray>您没有足够的经验点数传送到那里！
        <prefix> <gray>您至少需要<aqua><points></aqua>经验点！
  notEnoughMoney: |-
    <prefix> <gray>您的资金不足以传送到那里！
        <prefix> <gray>您至少需要<aqua><amount></aqua>！
  requestExpired: <prefix> <gray>您向<aqua><player></aqua>的传送请求已过期！
  noPlayerInput: <prefix> <gray>您必须输入玩家名称！
  blockSelf: <prefix> <gray>您不能阻止自己！
  noRequestsFromPlayer: <prefix> <gray>您没有来自<aqua><player></aqua>的任何待处理请求！
  invalidPageNo: <prefix> <gray>您输入了无效的页码！
  noHomeInput: <prefix> <gray>您必须包括一个家的名字！
  noSuchHome: <prefix> <gray>这个家不存在！
  noBedHome: <prefix> <gray>您没有设置任何床作为出生点！
  noBedHomeOther: <prefix> <aqua><player></aqua> <gray>没有设置任何床作为出生点！
  reachedHomeLimit: <prefix> <gray>您不能再设置更多的家了！
  homeAlreadySet: <prefix> <gray>您已经有一个叫做<aqua><home></aqua>的家了！
  noWarpInput: <prefix> <gray>您必须包括传送点的名称！
  noSuchWarp: <prefix> <gray>那个传送点不存在！
  warpAlreadySet: <prefix> <gray>已经有一个叫做<aqua><warp></aqua>的传送点了！
  noSuchWorld: <prefix> <gray>那个世界不存在！
  worldUnloaded: <prefix> <gray>抱歉，目标世界要么不存在，要么没有加载。请告诉服务器管理员！
  noLocation: <prefix> <gray>您没有任何可以传送回去的位置！
  notAPlayer: <prefix> <gray>您必须是玩家才能运行这个命令！
  noHomes: <prefix> <gray>您没有任何家！
  noHomesOther: <prefix> <aqua><player></aqua> <gray>没有任何家！
  tooFarAway: <prefix> <gray>传送目的地太远，所以您不能传送到那里！
  noRequestsSent: <prefix> <gray>无法向任何人发送请求 :(
  onCountdown: <prefix> <gray>在等待传送时，您不能使用此命令！
  noPermissionWarp: <prefix> <gray>您不能传送到<aqua><warp></aqua>！
  cantTPToWorld: <prefix> <gray>您不能在那个世界随机传送！
  cantTPToWorldLim: <prefix> <gray>您不能传送到<aqua><world></aqua>！
  tooFewArguments: <prefix> <gray>参数太少！
  invalidArgs: <prefix> <gray>参数无效！
  cantTPToPlayer: <prefix> <gray>您不能请求传送到<aqua><player></aqua>！
  noWarps: <prefix> <gray>目前没有任何传送点！
  noAccessHome: <prefix> <gray>目前您无法访问<aqua><home></aqua>！
  moveHomeFail: <prefix> <gray>家已经被移动，但数据没有成功存储。插件将尝试自行修复这个问题。
  setMainHomeFail: <prefix> <gray>主家已经被设置，但数据没有成功存储。插件将尝试自行修复这个问题。
  deleteHomeFail: <prefix> <gray>家已经被删除，但数据没有成功存储。插件将尝试自行修复这个问题。
  setHomeFail: <prefix> <gray>家已经被设置，但数据没有成功存储。插件将尝试自行修复这个问题。
  deleteWarpFail: <prefix> <gray>传送点已经被设置，但数据没有成功存储。插件将尝试自行修复这个问题。
  purgeWarpsFail: <prefix> <gray>无法清除传送点。请检查控制台以获取更多信息。
  purgeHomesFail: <prefix> <gray>无法清除家。请检查控制台以获取更多信息。
  homesNotLoaded: <prefix> <gray>此玩家的家还没有加载，请稍等片刻（甚至只需一秒钟）再试一次！
  noOfflineLocation: <prefix> <gray>没有找到<aqua><player></aqua>的离线位置！
  failedOfflineTeleport: <prefix> <gray>传送到离线玩家<aqua><player></aqua>失败！
  failedOfflineTeleportHere: <prefix> <gray>将离线玩家<aqua><player></aqua>传送到您的位置失败！
  alreadySearching: <prefix> <gray>已经在寻找传送位置！
  mirrorSpawnNoArguments: <prefix> <gray>没有指定任何世界/出生点！
  mirrorSpawnLackOfArguments: <prefix> <gray>您必须是玩家才能只指定一个世界 - 请指定一个世界和一个出生点以镜像玩家到那里！
  noSuchSpawn: <prefix> <gray>没有叫做<aqua><spawn></aqua>的出生点！
  cannotSetMainSpawn: <prefix> <gray>您只能将现有的出生点设为主出生点，而不是创建新的！
  cannotSetMainSpawnConsole: <prefix> <gray>由于您不是玩家，您只能将现有的出生点设为主出生点，而不是创建新的！
  nonAlphanumericSpawn: <prefix> <gray>出生点需要是字母数字的！
  removeSpawnNoArgs: <prefix> <gray>您必须指定要移除的出生点！
  noSuchPlugin: <prefix> <gray>此插件目前还不支持导入/导出！
  cantImport: <prefix> <gray>无法从<aqua><plugin></aqua>导入插件数据（确保它已启用并且是正确的作者）！
  cantExport: <prefix> <gray>无法从<aqua><plugin></aqua>导出插件数据（确保它已启用并且是正确的作者）！
  noPluginSpecified: <prefix> <gray>您需要指定一个插件来导入/导出！
  invalidOption: <prefix> <gray>这不是一个有效的导入/导出选项！
  notEnoughItems: |-
    <prefix> <gray>您没有足够的物品来传送到那里！
        <prefix> <gray>您至少需要<aqua><amount></aqua> <type>（个）！
  mirrorSpawnFail: <prefix> <gray>无法将<aqua><from></aqua>的出生点镜像到<aqua><spawn></aqua>！
  removeSpawnFail: <prefix> <gray>无法移除出生点<aqua><spawn></aqua>！
  setMainSpawnFail: <prefix> <gray>无法设置主出生点<aqua><spawn></aqua>！
  blockFail: <prefix> <gray>无法保存阻止<aqua><player></aqua>的区块！
  unblockFail: <prefix> <gray>无法保存解除阻止<aqua><player></aqua>的区块！
  noParticlePlugins: <prefix> <gray>此服务器上没有粒子插件！您需要至少一个（PlayerParticles）来使用此命令。
  notEnoughArgs: <prefix> <gray>您没有指定足够的参数来运行此命令！
  failedMapIconUpdate: <prefix> <gray>更新地图图标失败！请检查控制台以获取更多信息。
  setWarpFail: <prefix> <gray>设置传送点<warp>失败！
  teleportFailed: <prefix> <gray>抱歉，我们无法将您传送 :(
  randomLocFailed: <prefix> <gray>抱歉，我们找不到位置将您传送过去 :(
Info:
  tpOff: <prefix> <gray>已成功禁用传送请求！
  tpOn: <prefix> <gray>已成功启用传送请求！
  tpAdminOff: <prefix> <gray>已成功为<aqua><player></aqua>禁用传送请求！
  tpAdminOn: <prefix> <gray>已成功为<aqua><player></aqua>启用传送请求！
  requestSent: |2
        <prefix> <gray>已成功向<aqua><player></aqua>发送请求！
        <prefix> <gray>他们有<aqua><lifetime></aqua>时间来回应！
        <prefix> <gray>要取消请求，请使用<aqua>/tpcancel</aqua>。

                            <click:run_command:'/tpcancel <player>'><hover:show_text:'<red>点击这里取消请求。'><gray><bold>[取消]</hover></click>
  tpaRequestReceived: |2
        <prefix> <gray>玩家<aqua><player></aqua>想要传送到您这里！
        <prefix> <gray>如果您想接受，请使用<aqua>/tpayes</aqua>，如果不，请使用<aqua>/tpano</aqua>。
        <prefix> <gray>您有<aqua><lifetime></aqua>时间来回应它！

                            <click:run_command:'/tpayes <player>'><hover:show_text:'<green>点击这里接受请求。'><green><bold>[接受]</hover></click>             <click:run_command:'/tpano <player>'><hover:show_text:'<red>点击这里拒绝请求。'><red><bold>[拒绝]</red></bold></hover></click>
  tpaRequestHere: |2
        <prefix> <gray>玩家<aqua><player></aqua>想要将您传送到他们那里！
        <prefix> <gray>如果您想接受，请使用<aqua>/tpayes</aqua>，如果不，请使用<aqua>/tpano</aqua>。
        <prefix> <gray>您有<aqua><lifetime> 秒</aqua>时间来回应它！

                          <click:run_command:'/tpayes <player>'><hover:show_text:'<green>点击这里接受请求。'><green><bold>[接受]</bold></hover></click>             <click:run_command:'/tpano <player>'><hover:show_text:'<red>点击这里拒绝请求。'><red><bold>[拒绝]</red></bold></hover></click>
  blockPlayer: <prefix> <aqua><player> <gray>已被阻止。
  tpCancel: <prefix> <gray>您已取消您的传送请求。
  tpCancelResponder: <prefix> <aqua><player> <gray>已取消他们的传送请求。
  multipleRequestsCancel: <prefix> <gray>您有多个待处理的传送请求！点击以下之一进行取消：
  multipleRequestsIndex: <prefix> <click:run_command:<command> <player>><player></click>
  multipleRequestsList: <prefix> <gray>执行 /tpalist <页码> 来检查其他请求。
  multipleRequestAccept: <prefix> <gray>您有多个待处理的传送请求！点击以下之一来接受：
  multipleRequestDeny: <prefix> <gray>您有多个待处理的传送请求！点击以下之一来拒绝：
  requestDeclined: <prefix> <gray>您已拒绝传送请求！
  requestDeclinedResponder: <prefix> <gray><aqua><player></aqua> 已拒绝您的传送请求！
  requestDisplaced: <prefix> <gray>由于<aqua><player></aqua>收到了另一个请求，您的请求已被取消！
  deletedHome: <prefix> <gray>已成功删除家 <aqua><home></aqua>！
  deletedHomeOther: <prefix> <gray>已成功为 <aqua><player></aqua> 删除家 <aqua><home></aqua>！
  setHome: <prefix> <gray>已成功设置家 <aqua><home></aqua>！
  setHomeOther: <prefix> <gray>已成功为 <aqua><player></aqua> 设置家 <aqua><home></aqua>！
  setSpawn: <prefix> <gray>已成功设置出生点！
  setWarp: <prefix> <gray>已成功设置传送点 <aqua><warp></aqua>！
  deletedWarp: <prefix> <gray>已成功删除传送点 <aqua><warp></aqua>！
  purgeWarpsWorld: <prefix> <gray>已成功清除 <aqua><world></aqua> 中的所有传送点！
  purgeWarpsCreator: <prefix> <gray>已成功清除由 <aqua><player></aqua> 创建的所有传送点！
  purgeHomesWorld: <prefix> <gray>已成功清除 <aqua><world></aqua> 中的所有家！
  purgeHomesCreator: <prefix> <gray>已成功清除为 <aqua><player></aqua> 创建的所有家！
  searching: <prefix> <gray>正在寻找位置...
  unblockPlayer: <prefix> <gray>已成功解除阻止 <aqua><player></aqua>！
  reloadingConfig: <prefix> <gray>正在重新加载 <aqua>AdvancedTeleport</aqua> 的配置...
  reloadedConfig: <prefix> <gray>配置重新加载完成！
  warps: <aqua><bold>传送点 <dark_gray>» <reset>
  homes: <aqua><bold>家 <dark_gray>» <reset>
  homesOther: <aqua><bold><player> 的家 <dark_gray>» <reset>
  requestAccepted: <prefix> <gray>您已接受传送请求！
  requestAcceptedResponder: <prefix> <gray><aqua><player></aqua> 已接受传送请求！
  paymentVault: <prefix> <gray>您已支付 <aqua><amount></aqua>，现有余额为 <aqua><balance></aqua>！
  paymentEXP: <prefix> <gray>您已支付 <aqua><amount> EXP等级</aqua>，现有等级为 <aqua><levels></aqua>！
  paymentPoints: <prefix> <gray>您已支付 <aqua><amount> EXP点数</aqua>，现有点数为 <aqua><points></aqua>！
  createdWarpSign: <prefix> <gray>已成功创建传送点标志！
  createdRTPSign: <prefix> <gray>已成功创建随机传送点标志！
  createdSpawnSign: <prefix> <gray>已成功创建出生点标志！
  tpallRequestSent: <prefix> <gray>已成功向 <aqua><amount></aqua> 名玩家发送传送请求！
  teleportedToLoc: '<prefix> <gray>已成功将您传送到 <aqua><x></aqua>, <aqua><y></aqua>, <aqua><z></aqua>！(偏航:
    <aqua><yaw></aqua>, 俯仰: <aqua><pitch></aqua>, 世界: <aqua><world></aqua>)'
  teleportedToLocOther: '<prefix> <gray>已成功将 <aqua><player></aqua> 传送到 <aqua><x></aqua>,
    <aqua><y></aqua>, <aqua><z></aqua>！(偏航: <aqua><yaw></aqua>, 俯仰: <aqua><pitch></aqua>,
    世界: <aqua><world></aqua>)'
  movedWarp: <prefix> <gray>将传送点 <aqua><warp></aqua> 移动到您当前的位置！
  movedHome: <prefix> <gray>将家 <aqua><home></aqua> 移动到您当前的位置！
  movedHomeOther: <prefix> <gray>将 <aqua><player></aqua> 的家 <aqua><home></aqua> 移动到您的位置！
  setMainHome: <prefix> <gray>将 <aqua><home></aqua> 设为您的主要家！
  setAndMadeMainHome: <prefix> <gray>在您当前位置设置了 <aqua><home></aqua> 并将其设为您的主要家！
  setMainHomeOther: <prefix> <gray>为 <aqua><player></aqua> 将 <aqua><home></aqua> 设为其主要家！
  setAndMadeMainHomeOther: <prefix> <gray>在您当前位置为 <aqua><player></aqua> 设置了 <aqua><home></aqua>
    并将其设为其主要家！
  mirroredSpawn: <prefix> <gray>将<aqua><from></aqua>的出生点镜像到<aqua><spawn></aqua>了！
  setMainSpawn: <prefix> <gray>已将主出生点设置为<aqua><spawn></aqua>！如果没有其他出生点或权限覆盖，所有玩家都将被传送到那里。
  removedSpawn: <prefix> <gray>已移除出生点<aqua><spawn></aqua>！
  setSpawnSpecial: <prefix> <gray>已设置特殊出生点<aqua><spawn></aqua>！
  importStarted: <prefix> <gray>正在从<aqua><plugin></aqua>开始导入...
  importFinished: <prefix> <gray>从<aqua><plugin></aqua>导入完成！
  exportStarted: <prefix> <gray>正在开始导出到<aqua><plugin></aqua>...
  exportFinished: <prefix> <gray>导出到<aqua><plugin></aqua>完成！
  paymentItems: <prefix> <gray>您已为该传送支付了<aqua><amount> <type>(s)</aqua>！
  updateInfo: |-
    <prefix> <hover:show_text:'<aqua>当前版本 <dark_gray>» <gray><version>
    <aqua>新版本 <dark_gray>» <gray><new-version>
    <aqua>标题 <dark_gray>» <gray><title>'><click:open_url:'https://www.spigotmc.org/resources/advancedteleport.64139/'><gray>AdvancedTeleport 有更新可用！点击/悬停在这段文字上以获取更多信息。</click></hover>
  defaultParticlesUpdated: <prefix> <gray>已将默认等待粒子设置为您当前的粒子设置！
  specificParticlesUpdated: <prefix> <gray>已将<aqua><type></aqua>的等待粒子设置为您当前的粒子设置！
  mapIconUpdateClickTooltip: <prefix> <gray>已更新<aqua><name></aqua>的点击提示为<type>！地图应该很快就会更新。
  mapIconUpdateHoverTooltip: <prefix> <gray>已更新<aqua><name></aqua>的悬停提示为<type>！地图应该很快就会更新。
  mapIconUpdateIcon: <prefix> <gray>已更新<aqua><name></aqua>的图标为<type>！地图应该很快就会更新。
  mapIconUpdateSize: <prefix> <gray>已更新<aqua><name></aqua>的图标大小为<type>！地图应该很快就会更新。
  mapIconUpdateVisibility: <prefix> <gray>已更新<aqua><name></aqua>的图标可见性为<type>！地图应该很快就会更新。
  mirrorSpawnSame: <prefix> <gray><aqua><from></aqua>和<aqua><spawn></aqua>的出生点已经指向同一个地方了！不用担心
    :)
Tooltip:
  homes: <prefix> <gray>传送您到您的家：<aqua><home>
  warps: <prefix> <gray>传送您到传送点：<aqua><warp>
  location: |2-

    <aqua>X <dark_gray>» <gray><x>
    <aqua>Y <dark_gray>» <gray><y>
    <aqua>Z <dark_gray>» <gray><z>
    <aqua>世界 <dark_gray>» <gray><world>
Menu:
  Help:
    header: <aqua>・．<gray>━━━━━━━━━━━</gray> <dark_gray>❰</dark_gray> <bold>高级传送</bold>
      <gray><current_page>/<total_pages> <dark_gray>❱</dark_gray> <gray>━━━━━━━━━━━</gray>．・
    option: <dark_gray>» <aqua><usage></aqua> ~ <gray><description>
Descriptions:
  Subcommands:
    help: 发送帮助菜单，提供所有命令的完整列表。
    info: 发送有关插件的信息。
    import: 从另一个插件导入数据，以便在AT中使用。
    export: 将AT中的数据导出到另一个插件。
    reload: 重新加载插件的配置。
    clearcache: 清除RTP缓存。
    map:
      setclicktooltip: 设置在地图插件中点击AT图标时的提示（不包括Dynmap）。
      sethovertooltip: 设置在地图插件中悬停AT图标时的提示。
      seticon: 设置地图插件中AT图标的图像。
      setsize: 设置地图插件中AT图标的大小（不包括Dynmap）。
      setvisible: 设置在地图插件中点击时AT图标的可见性。
  at: AT的核心命令。
  tpa: 发送请求传送到玩家。
  tpahere: 发送请求让玩家传送到你这里。
  tpyes: 接受玩家的传送请求。
  tpno: 拒绝玩家的传送请求。
  tpcancel: 取消你对玩家的传送请求。
  toggletp: 允许或阻止玩家向你发送传送请求。
  tpon: 允许玩家向你发送传送请求。
  tpoff: 阻止玩家向你发送传送请求。
  tpblock: 阻止特定玩家向你发送传送请求。
  tpunblock: 允许被阻止的玩家再次向你发送传送请求。
  back: 传送你回到之前的位置。
  tpalist: 列出你当前的所有传送请求。
  tpo: 立即传送你到玩家那里。
  tpohere: 立即将玩家传送到你这里。
  tpall: 向服务器中的每个人发送传送请求到你这里。
  tploc: 传送你到特定位置。
  tpoffline: 传送你到离线玩家那里。
  tpofflinehere: 将离线玩家传送到你这里。
  tpr: 传送你到随机位置。
  warp: 传送你到指定的传送点。
  warps: 提供你可以传送到的传送点列表。
  setwarp: 在你的位置设置传送点。
  delwarp: 删除传送点。
  movewarp: 将传送点移动到新位置。
  spawn: 传送你到出生点。
  setspawn: 指定名称时设置一个出生点。
  mirrorspawn: 将一个世界中使用/spawn的人重定向到另一个出生点。
  setmainspawn: 将指定的出生点设为主出生点。如果它不存在，并且你有/setspawn权限，它将被创建。
  removespawn: 移除指定的出生点。如果没有指定，将移除你当前世界的出生点。
  home: 传送你到你的家。
  homes: 提供你设置的家的列表。
  sethome: 在你当前的位置设置家。
  delhome: 删除家。
  movehome: 将家移动到新位置。
  setmainhome: 在你的位置设置家或使现有家成为你的主要家。
  purge: 移除指定玩家或世界的所有传送点或家。
  particles: 将你当前的粒子选择移植到默认等待粒子配置，或者是命令配置。
Usages:
  Subcommands:
    help: /at help [分类|页面]
    info: /at info
    import: /at import <插件> [全部|家|最后位置|传送点|出生点|玩家]
    export: /at export <插件> [全部|家|最后位置|传送点|出生点|玩家]
    purge: /at purge <家|传送点> <玩家|世界> <玩家名称|世界名称>
    reload: /at reload
    clearcache: /at clearcache [世界]
    particles: /at particles [Tpa|Tpahere|家|Tpr|传送点|出生点|返回]
    map:
      setclicktooltip: /at map setclicktooltip <家|传送点|出生点> [家拥有者] <提示>
      sethovertooltip: /at map sethovertooltip <家|传送点|出生点> [家拥有者] <提示>
      seticon: /at map seticon <家|传送点|出生点> [家拥有者] <图像名称>
      setsize: /at map setsize <家|传送点|出生点> [家拥有者] <图像大小>
      setvisible: /at map setvisible <家|传送点|出生点> [家拥有者] <true|false>
  at: /at <命令>
  tpa: /tpa <玩家>
  tpahere: /tpahere <玩家>
  tpyes: /tpyes [玩家]
  tpno: /tpno [玩家]
  tpcancel: /tpcancel [玩家]
  toggletp: /toggletp
  tpon: /tpon
  tpoff: /tpoff
  tpblock: /tpblock <玩家> [原因]
  tpunblock: /tpunblock <玩家>
  back: /back
  tpalist: /tpalist
  tpo: /tpo <玩家>
  tpohere: /tpohere <玩家>
  tpall: /tpall
  tploc: /tploc <x|~> <y|~> <z|~> [偏航|~] [俯仰|~] [世界|~] [玩家] [精确|无飞行]
  tpoffline: /tpoffline <玩家>
  tpofflinehere: /tpofflinehere <玩家>
  tpr: /tpr [世界]
  warp: /warp <传送点>
  warps: /warps
  setwarp: /setwarp <名称>
  delwarp: /delwarp <名称>
  movewarp: /movewarp <名称>
  spawn: /spawn
  setspawn: /setspawn [ID]
  mirrorspawn: /mirrorspawn <目标点>|[来自世界] [目标点]
  setmainspawn: /setmainspawn [点]
  removespawn: /removespawn [点]
  home: /home [家]
  homes: /homes
  sethome: /sethome <名称>
  delhome: /delhome <家>
  movehome: /movehome <家>
  setmainhome: /setmainhome <家>
Usages-Admin:
  tpr: /tpr [世界] [玩家]
  home: /home [家]|<玩家> <家>
  homes: /homes [玩家]
  delhome: /delhome <家>|<玩家> <家>
  sethome: /sethome <名称>|<玩家> <名称>
  movehome: /movehome <家>|<玩家> <家>
  setmainhome: /setmainhome <家>|<玩家> <家>
  spawn: /spawn <ID>
Signs:
  bed: <blue><bold>[床]</bold></blue>
  home: <blue><bold>[家]</bold></blue>
  homes: <blue><bold>[家]</bold></blue>
  randomtp: <blue><bold>[随机传送]</bold></blue>
  spawn: <blue><bold>[出生点]</bold></blue>
  warp: <blue><bold>[传送点]</bold></blue>
  warps: <blue><bold>[传送点]</bold></blue>
Forms:
  tpahere-title: 传送到我这里请求
  tpahere-description: 选择一个玩家发送传送到我这里的请求。
  tpa-title: 传送请求
  tpa-description: 选择一个玩家发送传送请求。
  tpa-received-title: 传送请求
  tpa-received-description: 玩家<player>想要传送到您这里！
  tpa-received-accept: 接受
  tpa-received-deny: 拒绝
  tpahere-received-title: 传送到我这里请求
  tpahere-received-description: 玩家<player>希望您传送到他们那里！
  tpahere-received-accept: 接受
  tpahere-received-deny: 拒绝
  home-title: 家
  home-description: 选择一个家传送。
  sethome-title: 设置家
  sethome-description: 输入家的名字。
  delhome-title: 删除家
  delhome-description: 选择要删除的家。
  setmainhome-title: 设置主家
  setmainhome-description: 输入现有家的名字或新家的名字。
  movehome-title: 移动家
  movehome-description: 选择要移动的家。
  warp-title: 传送点
  warp-description: 选择一个传送点传送。
  delwarp-title: 删除传送点
  delwarp-description: 选择要删除的传送点。
  setwarp-title: 设置传送点
  setwarp-description: 输入传送点的名字。
  movewarp-title: 移动传送点
  movewarp-description: 选择要移动的传送点。
  tpblock-title: 阻止玩家
  tpblock-description: 选择一个玩家进行阻止。
  tpunblock-title: 解除阻止玩家
  tpunblock-description: 选择一个玩家进行解除阻止。
  tpcancel-title: 取消传送请求
  tpcancel-description: 选择一个请求来取消。
  tpo-title: 传送
  tpo-description: 选择一个玩家传送到他们那里。
  tpohere-title: 传送到这里
  tpohere-description: 选择一个玩家传送到您的位置。

```
