### ISSUE TITLE
[BUG] custom command permissions causes Warp and Warps to be unavalible

### ISSUE THREAD

**Issue by EnderMelody** [Niestrat99/AT-Rewritten#63]
### Description
After testing to make sure everything worked with the default settings, i changed the permissions for non op users. doing so made both Warp commands unavailable. I tried adding the other commands in but non of them fixed the problem either. Below is what I want to use.

default-permissions:
- at.member.core
- at.member.list
- at.member.tpa
- at.member.toggletp
- at.member.cancel
- at.member.unblock
- at.member.block
- at.member.yes
- at.member.no
- at.member.warp.*
- at.member.warps.*

### Reproducing
Change config for command permission.
launcher server and try to warp while non-OP

### Expected Behaviour
Warp to be usable by non-OPs

### Stacktraces
[latest.log](https://github.com/Niestrat99/AT-Rewritten/files/7874407/latest.log)

### Server
Use /version to fill out the following information.
 - Server Type: [Paper]
 - Server Version: [1.18.1]
 - Build: [147]

### Plugin Information
Use /version AdvancedTeleport to fill out this information.
- Plugin version: [Bukkit-5.5.7]

**Comment by Duffscs** [comment]
Try this in you permission.yml
```yml
server.basics:
  default: not-op
  description: "Default permissions."
  children:
    at.member.warp: true
    at.member.warps: true
    at.member.warp.use-sign: true
    at.member.warps.use-sign: true

```
